### ISSUE TITLE
Base class package "isrcore::Shell" is empty

### ISSUE THREAD

**Issue by TheFlea** [infobyte/evilgrade#11] opened 2016-07-31 14:16 UTC
Hello when i run evilgrade i get this. I am running Kali linux 2.0 mini.

Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.

:)

**Comment by mattaereal** [comment] 2016-08-17 17:31
Hi, we'll look into this, just replicated the issue. Thanks for the feedback!

**Comment by mattaereal** [comment] 2016-08-17 18:29
Hi again, I just downloaded the latest Kali linux available from the official website, installed the 4 modules needed from cpan, and this error is not showing.

Do you have the latest evilgrade version, and all the needed modules? If so, could you provide us with more information like how you're running evilgrade, perl version, etc?

Thanks again!

**Comment by kwiha** [comment] 2016-08-19 09:34
root@kali:~# apt-get install isr-evilgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  caribou-antler castxml gccxml gir1.2-clutter-gst-2.0 gir1.2-gkbd-3.0
  gir1.2-packagekitglib-1.0 gir1.2-xkl-1.0 gnome-icon-theme-symbolic
  gtk2-engines gucharmap java-wrappers libadns1 libapache2-mod-php5
  libasn1-8-heimdal libbasicusageenvironment0 libbind9-90
  libboost-filesystem1.58.0 libboost-python1.58.0 libboost-system1.58.0
  libboost-thread1.58.0 libcamel-1.2-54 libclutter-gst-2.0-0 libcrypto++9v5
  libdns100 libexporter-tiny-perl libgdict-1.0-9 libgif4 libgrilo-0.2-1
  libgroupsock1 libgssapi3-heimdal libgtkglext1 libgucharmap-2-90-7
  libhcrypto4-heimdal libhdb9-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhunspell-1.3-0 libhx509-5-heimdal libical1a
  libilmbase6v5 libisc95 libisccc90 libisccfg90 libjasper1 libkdc2-heimdal
  libkrb5-26-heimdal liblist-moreutils-perl liblivemedia23 libllvm3.7
  liblouis9 liblwres90 libntdb1 libonig2 libopenexr6v5 libpng12-0 libpoppler57
  libpth20 libqdbm14 libqmi-glib1 libquvi-scripts libquvi7 libregfi0
  libroken18-heimdal libsysfs2 libtask-weaken-perl libtrio2
  libusageenvironment1 libwebpdemux1 libwebpmux1 libwebrtc-audio-processing-0
  libwind0-heimdal libzip2 php5 php5-cli php5-common php5-json php5-mysql
  php5-readline python-adns python-characteristic python-ctypeslib
  python-distlib python-easygui python-ecdsa python-levenshtein python-lzma
  python-lzo python-metaconfig python-ntdb python-opengl python-pyatspi
  python-pyqtgraph python-qt4-gl python-tidylib ruby-rainbow ruby-rexec
  ruby2.2-dev system-config-printer
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  isr-evilgrade
0 upgraded, 1 newly installed, 0 to remove and 139 not upgraded.
Need to get 0 B/7,720 kB of archives.
After this operation, 13.8 MB of additional disk space will be used.
Selecting previously unselected package isr-evilgrade.
(Reading database ... 343315 files and directories currently installed.)
Preparing to unpack .../isr-evilgrade_2.0.7+git20160629-0kali1_all.deb ...
Unpacking isr-evilgrade (2.0.7+git20160629-0kali1) ...
Setting up isr-evilgrade (2.0.7+git20160629-0kali1) ...
             
root@kali:~# evilgrade 
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:~# uname -a
Linux kali 4.6.0-kali1-686-pae #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux
root@kali:~# perl -v

This is perl 5, version 22, subversion 2 (v5.22.2) built for i686-linux-gnu-thread-multi-64int
(with 67 registered patches, see perl -V for more detail)

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

root@kali:~#

**Comment by MarcosAlarconRivas** [comment] 2016-08-19 11:31
Same here with another architecture:

# apt-get install isr-evilgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
isr-evilgrade is already the newest version (2.0.7+git20160629-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# uname -a
Linux CFVTesting 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

# evilgrade 
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.

**Comment by mattaereal** [comment] 2016-08-19 14:09
Would you mind running evilgrade from the full path where it is installed?

This is because evilgrade is meant to be run on the main folder of the project, since all the relative paths are pointing to folders inside the project.

**Comment by kwiha** [comment] 2016-08-19 14:15
root@kali:~# find / -name evilgrade
/usr/share/isr-evilgrade/evilgrade
/usr/bin/evilgrade
root@kali:~# /usr/share/isr-evilgrade/evilgrade
Can't locate isrcore/shellz.pm in @INC (you may need to install the isrcore::shellz module) (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .) at /usr/share/isr-evilgrade/evilgrade line 24.
BEGIN failed--compilation aborted at /usr/share/isr-evilgrade/evilgrade line 24.
root@kali:~# /usr/bin/evilgrade
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:~# cd /usr/bin/
root@kali:/usr/bin# evilgrade 
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:/usr/bin# cd ~/Downloads/
root@kali:~/Downloads# git clone https://github.com/infobyte/evilgrade.git
Cloning into 'evilgrade'...
remote: Counting objects: 598, done.
remote: Total 598 (delta 0), reused 0 (delta 0), pack-reused 598
Receiving objects: 100% (598/598), 7.82 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (265/265), done.
Checking connectivity... done.
root@kali:~/Downloads# ls
evilgrade
root@kali:~/Downloads# cd evilgrade/
root@kali:~/Downloads/evilgrade# ls
agent  certs  docs  evilgrade  extra  include  isrcore  modules  README.md
root@kali:~/Downloads/evilgrade# ./evilgrade 
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:~/Downloads/evilgrade#

**Comment by mattaereal** [comment] 2016-08-19 18:58
Thanks again. I'll look into it. I can't seem to replicate it. I downloaded the latest kali linux virtual machine and did a git clone without an issue.

**Comment by maxnovawind75** [comment] 2016-08-19 19:05
hi, i have also the same error with this tool. i don't know why.

**Comment by kwiha** [comment] 2016-08-19 19:07
@mattaereal I downloaded the VM. After downloading the latest kali VM i did apt-get update && apt-get upgrade && apt-get dist-upgrade and then installed evilgrade. I tried both the git clone and apt-get install isr-evilgrade way. Both are still failing.

**Comment by mattaereal** [comment] 2016-08-19 19:26
I think the aptitude package is messing up evilgrade's way to load modules, or something else I can't figure out.

I just downloaded *again* the latest kali linux: https://images.offensive-security.com/virtual-images/Kali-Linux-2016.1-vm-amd64.7z, did a git clone, and it's working like a charm.

Don't install evilgrade from the aptitude repository, git clone it on a new clean vm if you can, else remove purge and try the git cloned again.

Thanks!

**Comment by mattaereal** [comment] 2016-08-19 19:36
Can you show me the output of *uname* -a and *perl -v*?

**Comment by maxnovawind75** [comment] 2016-08-19 19:46
root@sharingan-PC:~/Bureau/evilgrade-2.0.7# perl -v

This is perl 5, version 22, subversion 2 (v5.22.2) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

root@sharingan-PC:~/Bureau/evilgrade-2.0.7# uname -a
Linux sharingan-PC 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by maxnovawind75** [comment] 2016-08-19 19:47
i don't use vm

**Comment by maxnovawind75** [comment] 2016-08-19 19:48
i thinks there are some conflict with lastest update of kali

**Comment by kwiha** [comment] 2016-08-19 19:57
root@kali:~/Downloads/evilgrade# apt-get purge isr-evilgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  caribou-antler castxml gccxml gir1.2-clutter-gst-2.0 gir1.2-gkbd-3.0
  gir1.2-packagekitglib-1.0 gir1.2-xkl-1.0 gnome-icon-theme-symbolic gtk2-engines
  gucharmap java-wrappers libadns1 libapache2-mod-php5 libasn1-8-heimdal
  libbasicusageenvironment0 libbind9-90 libboost-filesystem1.58.0
  libboost-python1.58.0 libboost-system1.58.0 libboost-thread1.58.0 libcamel-1.2-54
  libclass-factory-util-perl libclass-singleton-perl libclutter-gst-2.0-0
  libcrypto++9v5 libdatetime-format-builder-perl libdatetime-format-iso8601-perl
  libdatetime-format-strptime-perl libdatetime-locale-perl libdatetime-perl
  libdatetime-timezone-perl libdns100 libexporter-tiny-perl libgdict-1.0-9 libgif4
  libgrilo-0.2-1 libgroupsock1 libgssapi3-heimdal libgtkglext1 libgucharmap-2-90-7
  libhcrypto4-heimdal libhdb9-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhunspell-1.3-0 libhx509-5-heimdal libical1a libilmbase6v5 libisc95 libisccc90
  libisccfg90 libjasper1 libkdc2-heimdal libkrb5-26-heimdal liblist-moreutils-perl
  liblivemedia23 libllvm3.7 liblouis9 liblwres90 libnamespace-autoclean-perl libntdb1
  libonig2 libopenexr6v5 libparams-validate-perl libpng12-0 libpoppler57 libpth20
  libqdbm14 libqmi-glib1 libquvi-scripts libquvi7 libregfi0 libroken18-heimdal
  librpc-xml-perl libsysfs2 libtask-weaken-perl libtrio2 libusageenvironment1
  libwebpdemux1 libwebpmux1 libwebrtc-audio-processing-0 libwind0-heimdal libzip2
  php5 php5-cli php5-common php5-json php5-mysql php5-readline python-adns
  python-characteristic python-ctypeslib python-distlib python-easygui python-ecdsa
  python-levenshtein python-lzma python-lzo python-metaconfig python-ntdb
  python-opengl python-pyatspi python-pyqtgraph python-qt4-gl python-tidylib
  ruby-rainbow ruby-rexec ruby2.2-dev system-config-printer
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  isr-evilgrade*
0 upgraded, 0 newly installed, 1 to remove and 139 not upgraded.
After this operation, 13.8 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 343739 files and directories currently installed.)
Removing isr-evilgrade (2.0.7+git20160629-0kali1) ...
root@kali:~/Downloads/evilgrade# ./evilgrade 
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:~/Downloads/evilgrade# cd ..
root@kali:~/Downloads# rm -rf evilgrade/
root@kali:~/Downloads# ls
root@kali:~/Downloads# git clone https://github.com/infobyte/evilgrade.git
Cloning into 'evilgrade'...
remote: Counting objects: 598, done.
remote: Total 598 (delta 0), reused 0 (delta 0), pack-reused 598
Receiving objects: 100% (598/598), 7.82 MiB | 135.00 KiB/s, done.
Resolving deltas: 100% (265/265), done.
Checking connectivity... done.
root@kali:~/Downloads# cd evilgrade/
root@kali:~/Downloads/evilgrade# ls
agent  certs  docs  evilgrade  extra  include  isrcore  modules  README.md
root@kali:~/Downloads/evilgrade# ./evilgrade 
Base class package "isrcore::Shell" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .).
 at isrcore/shellz.pm line 29.
BEGIN failed--compilation aborted at isrcore/shellz.pm line 29.
Compilation failed in require at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:~/Downloads/evilgrade# uname -a
Linux kali 4.6.0-kali1-686-pae #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux
root@kali:~/Downloads/evilgrade# perl -v

This is perl 5, version 22, subversion 2 (v5.22.2) built for i686-linux-gnu-thread-multi-64int
(with 67 registered patches, see perl -V for more detail)

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

root@kali:~/Downloads/evilgrade#

**Comment by mattaereal** [comment] 2016-08-19 20:26
I can't seem to reproduce the error on the latest VMs of Kali linux 2016.1. But I have an older VM of Kali Linux that is giving me the same error and I still don't know why. Maybe related to perl, not sure yet. Currently updating that old kali up-to-date to see what happens.

Thanks again!

**Comment by mattaereal** [comment] 2016-08-19 21:11
Just tried it on a friend's personal computer, based on Ubuntu 12.04, perl 5.14 and worked. Also on my Arch linux. Still don't know what triggers this.

**Comment by maxnovawind75** [comment] 2016-08-19 22:00
which 4 modules cpan your tool require ?

**Comment by kwiha** [comment] 2016-08-19 22:09
Well it works on my back track no problem. When it comes to this tool I'm using back track

**Comment by mattaereal** [comment] 2016-08-19 23:09
@maxnovawind75 The following ones, but it seems to have nothing to do with it.
`
    Data::Dump
    Digest::MD5
    Time::HiRes
    RPC::XML
`

@kwiha If you by any chance notice what would be the main difference between the two setups, please let me know, I'd really appreciate it.

**Comment by maxnovawind75** [comment] 2016-08-19 23:14
yes , i check your doc and install these four modules with cpan shell but still not working. i really like to know if this tool can run in kali 2.0 .

**Comment by BBY203** [comment] 2016-08-20 14:50
Hello, I've found a solution to this error.
First, open the evilgrade file with a text editor, then add the line "use isrcore::Shell;" to above of the "use isrcore::shellz;" line. So it should look like

**Comment by BBY203** [comment] 2016-08-20 14:53
Sorry because of separated comments, accidentally clicked to comment button :)
It should look like this;
...snip
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# '''
##
use isrcore::Shell;
use isrcore::shellz;

&main;
...snip
Cheers!

**Comment by BBY203** [comment] 2016-08-20 14:58
... Sorry I messed it up a little I'm such a noob but it will look like

use isrcore::Shell;
use isrcore::shellz;

**Comment by maxnovawind75** [comment] 2016-08-20 15:08
yes it's work thanks man

**Comment by maxnovawind75** [comment] 2016-08-20 15:50
but meanwhile i have this error when i set a agent 
Error: [WEBSERVER] - Cant't create a listening socket: IO::Socket::INET: Address already in use
??

**Comment by BBY203** [comment] 2016-08-20 16:06
Hmm... Maybe try to use another port? What is the exact command are you using to set an agent?

**Comment by maxnovawind75** [comment] 2016-08-20 16:10
set agent '["<$OUT$>/root/agent.exe<%OUT%>"]' 
my agent setting : lhost:myinternal ip lport:4444
it find my agent but something wrong with the port i don't know why ?

**Comment by BBY203** [comment] 2016-08-20 16:14
It seems like there is already a service running on the port 4444 change it to something between 50000-65530(just to make sure, as anything above the 50000 port is rare) and see if that works

**Comment by maxnovawind75** [comment] 2016-08-20 16:27
i have always the same problem

**Comment by maxnovawind75** [comment] 2016-08-20 16:43
nevermind i find a solution you must stop apache2 it's logic ^^

**Comment by mattaereal** [comment] 2016-08-20 18:35
Thanks for the feeback @BBY203. That did the trick. I thought I tried that, but I may have got dizzy between all the vms and the testing.

@maxnovawind75 The port you were using is already in use, this means you have probably left a service up, or you got another service using a port you're trying to open. I always stop apache and server dns before starting evilgrade. I got myself a bash script which 'kills/stops' dns and http server before starting evilgrade, in case it did not stop properly (supposing you're not using an http server for some other purpose).

Thanks everybody for the support. Already pushed and tested. Closing this issue, please open a new one if you want to talk about a different topic.

Cheers!

**Closed by mattaereal** 2016-08-20 18:35 UTC

**Comment by d4rkn0** [comment] 2016-10-14 20:15
i have the same problem .. i tried to install evilgrade by apt but i got the error message .. also with the git version i got the error message.

```
root@kali:/home/d4rkn0# which evilgrade 
/usr/bin/evilgrade
root@kali:/home/d4rkn0# evilgrade 
Can't locate isrcore/Shell.pm in @INC (you may need to install the isrcore::Shell module) (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/i386-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base) at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.
root@kali:/home/d4rkn0# 
```

```
root@kali:/home/d4rkn0/Downloads/evilgrade# ./evilgrade 
Can't locate isrcore/Shell.pm in @INC (you may need to install the isrcore::Shell module) (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/i386-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base) at ./evilgrade line 25.
BEGIN failed--compilation aborted at ./evilgrade line 25.
root@kali:/home/d4rkn0/Downloads/evilgrade# 
```

**Comment by DenverDaveH** [comment] 2016-11-06 23:52
I am getting the same issue as well. I did a dist-upgrade. 
oot@kali:~/evilgrade# perl -v

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi
(with 60 registered patches, see perl -V for more detail)

Copyright 1987-2016, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

root@kali:~/evilgrade# uname -a
Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.8-1kali1 (2016-10-24) x86_64 GNU/Linux

I have this in the evilgrade file:
use isrcore::Shell;
use isrcore::shellz;

root@kali:~/evilgrade# ./evilgrade 
Can't locate isrcore/Shell.pm in @INC (you may need to install the isrcore::Shell module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./evilgrade line 25.
BEGIN failed--compilation aborted at ./evilgrade line 25.

I then thought to find the Shell.pm file:
oot@kali:/# find . -name Shell.pm
./usr/share/perl/5.24.1/CPAN/Shell.pm
./usr/share/perl/5.22.2/CPAN/Shell.pm
./root/evilgrade/isrcore/Shell.pm

It appears the script is not finding the Shell.pm due to the CPAN directory being in the path of Shell.pm. Given there are 2 versions of Perl installed. 

And the last one is not being found either, for some reason. 

Any suggestions?

**Comment by shillingg** [comment] 2016-11-07 00:47
This problem still exits. I have the error on a VirtualBox copy of Kali 2016 and on a hardrive installed copy of Kali 2016. The Kali's are installed on two different machines. I've tried the install with git clone https://github.com/infobyte/evilgrde.git and the apt-get install isr-evilgrade methods. No errors seen on the install. Both Kali's are running on 64-bit machines. I can also verify that adding use 

isrcore::Shell;      to the evilgrade file doesn't fix the problem. 

root@kali:~# evilgrade
Can't locate isrcore/Shell.pm in @INC (you may need to install the isrcore::Shell module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./evilgrade line 24.
BEGIN failed--compilation aborted at ./evilgrade line 24.

root@kali:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

**Comment by rpanov** [comment] 2018-07-23 19:15
solution for "BEGIN failed -- compilation aborted at ./evilgrade line 24." or "line 25"

cp -r iscore /etc/perl

**Comment by PresidentBarnum** [comment] 2019-01-31 02:45
rpanov,

From...

root@kali:/evilgrade# cp -r isrcore /etc/perl

Thank you so much!  Works like a charm.

**Comment by bddarknight** [comment] 2019-02-10 09:44
> solution for "BEGIN failed -- compilation aborted at ./evilgrade line 24." or "line 25"
> 
> cp -r iscore /etc/perl

Thanks man! Works like a charm...

**Comment by f-amato** [comment] 2021-07-15 10:50
For mac user: sudo cp -rp isrcore /Library/Perl/5.30
